version: 1
# Local distribution config for markdownlint-trap
# Copies configuration files to consumer projects
# Edit this file to customize distribution targets

defaults:
  cleanDest: false  # Preserve existing configs by default
  merge: true       # Merge JSON settings instead of overwriting
  createDirs: true  # Create missing parent directories

# Targets of type "local" copy files to local directories
# Fields:
# - name: label for logging
# - enabled: boolean to activate (set to true to use)
# - type: must be "local"
# - src: source file (relative to repo root or absolute)
# - dest: destination path (supports wildcards) or array of paths
# - merge: merge JSON files instead of replacing (default: true for JSON)
# - cleanDest: delete destination before copying (default: false)
# - createDirs: create missing parent directories (default: true)
#
# WILDCARD EXAMPLES:
# - dest: ~/Projects/*/.vscode/settings.json       # All projects
# - dest: ../sibling-project/.vscode/settings.json # Specific project
# - dest:                                          # Multiple destinations
#     - ~/Projects/docs-*/.vscode/settings.json
#     - ~/Work/api-docs/.vscode/settings.json

targets:
  # --------------------------------------
  # VS Code Settings
  # --------------------------------------
  
  # Basic preset - minimal rules
  - name: vscode-basic
    enabled: false
    type: local
    src: templates/vscode-settings-basic.jsonc
    dest:
      # Edit this list to target your projects
      # - ~/Projects/my-project/.vscode/settings.json
    merge: true
    cleanDest: false

  # Recommended preset - balanced strictness
  - name: vscode-recommended
    enabled: true
    type: local
    src: templates/vscode-settings-recommended.jsonc
    dest:
      - ~/Projects/*/.vscode/settings.json  # All projects (wildcard)
    merge: true
    cleanDest: false

  # Strict preset - all rules enabled
  - name: vscode-strict
    enabled: false
    type: local
    src: templates/vscode-settings-strict.jsonc
    dest:
      # Edit this list to target your projects
      # - ~/Projects/api-docs/.vscode/settings.json
    merge: true
    cleanDest: false

  # --------------------------------------
  # markdownlint-cli2 Configuration
  # --------------------------------------
  
  # Basic CLI config
  - name: cli-basic
    enabled: false
    type: local
    src: templates/markdownlint-cli2-basic.jsonc
    dest:
      # Edit this list to target your projects
      # - ~/Projects/my-project/.markdownlint-cli2.jsonc
    cleanDest: false

  # Recommended CLI config
  - name: cli-recommended
    enabled: true
    type: local
    src: templates/markdownlint-cli2-recommended.jsonc
    dest:
      - ~/Projects/*/.markdownlint-cli2.jsonc  # All projects
    cleanDest: false

  # Strict CLI config
  - name: cli-strict
    enabled: false
    type: local
    src: templates/markdownlint-cli2-strict.jsonc
    dest:
      # Edit this list to target your projects
      # - ~/Projects/api-docs/.markdownlint-cli2.jsonc
    cleanDest: false

# --------------------------------------
# Global Installation
# --------------------------------------
# Install markdownlint-trap and markdownlint-cli2 globally
# This enables usage in ALL projects (including non-Node.js projects)
globalInstall:
  enabled: true
  linkLocal: true  # Use npm link for local development (false would use npm install -g)

# --------------------------------------
# NPM Package Installation (per-project)
# --------------------------------------
# Automatically install npm packages in target projects
# NOTE: Set enabled to false until markdownlint-trap is published to npm
# For local development, global installation + distribution is recommended
npmInstall:
  enabled: false  # Disabled: use globalInstall instead for local development
  packages:
    - markdownlint-trap
    - markdownlint-cli2
  projectDirs:
    - ~/Projects/*

# USAGE:
# 1. Edit the 'dest' paths above to point to your projects
# 2. Set 'enabled: true' for the targets you want to use
# 3. Configure npmInstall section to install dependencies
# 4. Run 'npm run dist:local:dry' to preview changes
# 5. Run 'npm run dist:local' to apply changes and install packages
