name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint
      - run: npx markdownlint-cli2 "**/*.md" "!.windsurf/**"
      - run: npm test
      - run: npm run test:performance
        name: Run performance tests
